# Generated by Django 5.2.13 on 2026-04-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_channels', '0001_initial'),
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmember',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat_messages.message'),
        ),
    ]
